name: Build Ghidra Plugin

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  GHIDRA_VER: "10.3"
  GHIDRA_RELEASE_DATE: "20230510"
  PLUGIN_NAME: "GhidraLookup"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Ghidra
        run: |
          echo "Downloading Ghidra ${GHIDRA_VER} (${GHIDRA_RELEASE_DATE})"
          GHIDRA_ZIP="ghidra_${GHIDRA_VER}_PUBLIC_${GHIDRA_RELEASE_DATE}.zip"
          GHIDRA_URL="https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_${GHIDRA_VER}_build/${GHIDRA_ZIP}"
          
          if ! wget -q --spider "$GHIDRA_URL"; then
            echo "::error::Ghidra download URL not found: $GHIDRA_URL"
            exit 1
          fi
          wget --progress=dot:giga "$GHIDRA_URL"
          echo "Download complete, verifying zip..."
          
          if ! unzip -q -t "$GHIDRA_ZIP"; then
            echo "::error::Downloaded Ghidra zip is corrupted"
            exit 1
          fi
          unzip -q "$GHIDRA_ZIP"
          echo "GHIDRA_INSTALL_DIR=$(pwd)/ghidra_${GHIDRA_VER}_PUBLIC" >> $GITHUB_ENV
          echo "Ghidra installed to $GHIDRA_INSTALL_DIR"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: |
          echo "Using Ghidra installation at: $GHIDRA_INSTALL_DIR"
          gradle build

      - name: Submit dependencies
        if: github.event_name == 'push'  # Only submit on push, not PRs
        uses: gradle/actions/dependency-submission@v4
        with:
          # Optional: Add any specific dependency submission config here
          github-token: ${{ secrets.GITHUB_TOKEN }}
