name: Build Ghidra Plugin

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  GHIDRA_VER: "10.3"
  GHIDRA_RELEASE_DATE: "20230510"
  PLUGIN_NAME: "GhidraLookup"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Ghidra
        id: download-ghidra
        run: |
          echo "Downloading Ghidra ${GHIDRA_VER} (${GHIDRA_RELEASE_DATE})"
          GHIDRA_ZIP="ghidra_${GHIDRA_VER}_PUBLIC_${GHIDRA_RELEASE_DATE}.zip"
          GHIDRA_URL="https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_${GHIDRA_VER}_build/${GHIDRA_ZIP}"
          
          if ! wget -q --spider "$GHIDRA_URL"; then
            echo "::error::Ghidra download URL not found: $GHIDRA_URL"
            exit 1
          fi

          wget --progress=dot:giga "$GHIDRA_URL"
          echo "Download complete, verifying zip..."
          
          if ! unzip -q -t "$GHIDRA_ZIP"; then
            echo "::error::Downloaded Ghidra zip is corrupted"
            exit 1
          fi

          unzip -q "$GHIDRA_ZIP"
          echo "GHIDRA_INSTALL_DIR=$(pwd)/ghidra_${GHIDRA_VER}_PUBLIC" >> $GITHUB_ENV
          echo "Ghidra installed to $GHIDRA_INSTALL_DIR"

      - name: Verify Ghidra installation
        run: |
          if [ ! -d "$GHIDRA_INSTALL_DIR" ]; then
            echo "::error::Ghidra installation directory not found"
            exit 1
          fi
          echo "Ghidra found at: $GHIDRA_INSTALL_DIR"
          ls -la "$GHIDRA_INSTALL_DIR/Ghidra/Features/Base/lib/"

      - name: Prepare build environment
        run: |
          mkdir -p build dist
          echo "Build directories created"

      - name: Detect plugin main class
        id: detect-plugin-class
        run: |
          set -euo pipefail  # Enable strict error handling
          
          # Search for plugin entry point using proper Ghidra conventions
          PLUGIN_CLASS=$(find src/main/java/ -name "*.java" -print0 | \
            xargs -0 grep -l -m 1 '@Plugin\|extends Plugin' | \
            head -1)

          if [[ -z "$PLUGIN_CLASS" ]]; then
            echo "::error::No plugin class found (looking for @Plugin annotation or Plugin extension)"
            exit 1
          fi

          # Convert path to fully qualified class name
          CLASS_NAME=$(echo "$PLUGIN_CLASS" | \
            sed 's/^src\/main\/java\///' | \
            sed 's/\.java$//' | \
            tr '/' '.')

          echo "Detected plugin class: $CLASS_NAME"
          
          # Verify the class contains required plugin info
          if ! grep -q '@PluginInfo' "$PLUGIN_CLASS"; then
            echo "::error::Plugin class missing required @PluginInfo annotation"
            exit 1
          fi

          echo "PLUGIN_MAIN_CLASS=$CLASS_NAME" >> $GITHUB_ENV
          echo "PLUGIN_ENTRY_FILE=$PLUGIN_CLASS" >> $GITHUB_ENV

      - name: Compile plugin
        run: |
          echo "Compiling plugin sources..."
          gradle
